spring.main.sources: dk.dma.enav.integration.aton.AtonInRouter

logging:
  level.org.apache.camel.component.file: DEBUG
  level.org.apache.camel.component.properties: DEBUG

couchdb:
#  host: localhost
  host: 192.168.99.100
  port: 5984
  name: aton
  username: embryo
  password: embryo


---
spring:
    profiles: unittest

shape.source.dir: target/aton
